name: LIVE365
description: Next TikTok App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  lottie: ^1.4.1
  fijkplayer: ^0.10.1
  # 基础的点击
  tapped: ^2.0.0
  get: ^4.6.5
  http: ^0.13.5
  share:
  country_list_pick: 1.0.1+6
  safemap: ^2.1.0
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  firebase_database: ^9.1.1
  cloud_firestore: ^3.4.4
  firebase_storage: ^10.3.5
  google_sign_in: ^5.4.1
  cached_network_image: ^3.2.1
  webview_flutter: ^3.0.4
  shared_preferences: ^2.0.15
  http_auth: ^1.0.1
  flutter_launcher_icons: ^0.10.0
  agora_rtc_engine: ^5.3.0
  agora_rtm: ^1.1.1
  sliding_up_panel: ^2.0.0+1
  wakelock: ^0.6.2
  permission_handler: ^10.0.0
  url_launcher: ^6.1.5
  bottom_navy_bar: 6.0.0
  font_awesome_flutter: ^10.1.0
  gradient_text: 1.0.2
  image_picker: ^0.8.5+3
  flare_flutter: ^3.0.2
  random_color: ^1.0.6-nullsafety
  responsive_builder: ^0.4.2
  marquee: ^2.2.3
  camera: ^0.10.0+1
  carousel_slider: ^4.1.1
  stacked_services: ^0.9.5
  get_it: ^7.2.0
  stacked: ^2.3.15
  path_provider: ^2.0.11
  path: ^1.8.1
  open_file: ^3.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  line_icons: ^2.0.1
  video_player: ^2.4.6
  flutter_svg: ^1.1.3
  intl: ^0.17.0
  date_range_picker: ^1.0.5
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  flutter_auth_buttons: ^0.5.0
  dio: ^4.0.6
  uuid: ^3.0.6
  timeago: ^3.3.0
  like_button: ^2.0.4
  image_cropper: ^3.0.0
  flutter_icons: ^1.1.0
  percent_indicator: ^4.2.2
  fluttertoast: ^8.0.9
  animations: ^2.0.3
  image: ^3.2.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  modal_progress_hud: ^0.1.3
  flutter_facebook_auth: ^4.4.1
  flutter_facebook_login: ^3.0.0
  screen: ^0.0.5 # keeping screen on

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gift/
    - assets/lotties/

fonts:
  fonts:
    - asset: assets/fonts/SFProDispaly-Regular.ttf
    - asset: assets/fonts/SFProDisplay-Black.ttf
    - asset: assets/fonts/SFProDisplay-Blod.ttf
      weight: 700
    - asset: assets/fonts/SFProDisplay-Heavy.ttf
    - asset: assets/fonts/SFProDisplay-Light.ttf
      weight: 300
    - asset: assets/fonts/SFProDisplay-Medium.ttf
    - asset: assets/fonts/SFProDisplay-semibold.ttf
    - asset: assets/fonts/SFProDisplay-Thin.ttf
    - asset: assets/fonts/SFProDisplay-Ultralight.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
